name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create .env file
      run: |
        echo "STRIPE_SECRET_KEY=sk_test_dummy" > .env
        echo "STRIPE_WEBHOOK_SECRET=whsec_dummy" >> .env
        echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_dummy" >> .env
        cp .env backend/.env

    - name: Build Docker images
      run: docker-compose build

    - name: Start containers
      run: docker-compose up -d

    - name: Wait for services
      run: |
        sleep 30
        docker-compose ps

    - name: Check backend health
      run: |
        curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:3001 || exit 1

    - name: Check frontend health
      run: |
        curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:3000 || exit 1

    - name: Show logs on failure
      if: failure()
      run: docker-compose logs

    - name: Stop containers
      run: docker-compose down

